
source "googlecompute" "autogenerated_1" {
  account_file  = "${var.chave}"
  communicator  = "winrm"
  disk_size     = "50"
  image_name    = "windows-server-winrm-2019"
  instance_name = "homolog-windows-server-adfs"
  machine_type  = "n1-highcpu-2"
  metadata = {
    windows-startup-script-cmd = "winrm quickconfig -quiet & net user /add packer_user & net localgroup administrators packer_user /add & winrm set winrm/config/service/auth @{Basic=\"true\"}"
  }
  
  project_id     = "${var.projeto}"
  source_image   = "windows-server-2019-dc-v20220314"
  winrm_insecure = true
  winrm_use_ssl  = true
  winrm_username = "packer_user"
  zone           = "us-east1-b"
}

build {
  sources = ["source.googlecompute.autogenerated_1"]

  provisioner "powershell" {
    scripts = ["config-user-adm.ps1", "config-winrm-ansible.ps1"]
  }

}
