---
- name: Cria Ambiente Active Directory com Dominio
  hosts: ad
  vars:
    temp_address: ${ip_instancia_ad}
    dc_address: ${ip_instancia_ad}
    dc_netmask_cidr: 24
    dc_gateway: ${ip_instancia_ad}
    dc_hostname: 'bookshelf-ad'
    domain_name: "example-gcp.local"
    local_admin: '.\administrator'
    temp_password: 'P@ssw0rd'
    dc_password: 'P@ssw0rd'
    recovery_password: 'P@ssw0rd'
    upstream_dns_1: 8.8.8.8
    upstream_dns_2: 8.8.4.4
    reverse_dns_zone: "172.16.108.0/24"
    ntp_servers: "0.us.pool.ntp.org,1.us.pool.ntp.org,2.us.pool.ntp.org,3.us.pool.ntp.org"
  gather_facts: no
  
  tasks:
  - name: Aguardando Instancia ficar disponivel
    wait_for_connection:
      timeout: 900
    delegate_to: '{{ dc_address }}'

  - name: Config IP Estatico
    win_shell: "(new-netipaddress -InterfaceAlias Ethernet0 -IPAddress {{ dc_address }} -prefixlength {{dc_netmask_cidr}} -defaultgateway {{ dc_gateway }})"
    delegate_to: '{{ temp_address }}'  
    ignore_errors: True 

  - name: Config Senha Admin
    win_user:
      name: administrator
      password: "{{dc_password}}"
      state: present
    delegate_to: '{{ dc_address }}'
    ignore_errors: True  
 
  - name: Aguardando o WinRM ficar disponivel na instancia 
    wait_for_connection:
      timeout: 900
    delegate_to: '{{ dc_address }}'

  - name: Config DNS
    win_dns_client:
      adapter_names: '*'
      ipv4_addresses:
      - '{{ upstream_dns_1 }}'
      - '{{ upstream_dns_2 }}'
    delegate_to: '{{ dc_address }}'

  - name: Parando time service
    win_service:
      name: w32time
      state: stopped
    delegate_to: '{{ dc_address }}'

  - name: Config NTP Servers
    win_shell: 'w32tm /config /syncfromflags:manual /manualpeerlist:"{{ntp_servers}}"'
    delegate_to: '{{ dc_address }}'

  - name: Inicia time service
    win_service:
      name: w32time
      state: started  
    delegate_to: '{{ dc_address }}'

  - name: Desativando firewall da instancia
    win_firewall:
      state: disabled
      profiles:
      - Domain
      - Private
      - Public
    tags: disable_firewall
    delegate_to: '{{ dc_address }}'

  - name: Mudando o hostname da Instancia 
    win_hostname:
      name: '{{ dc_hostname }}'
    register: res
    delegate_to: '{{ dc_address }}'

  - name: Reiniciando Instancia
    win_reboot:
    when: res.reboot_required   
    delegate_to: '{{ dc_address }}'

  - name: Instalando Active Directory
    win_feature: >
         name=AD-Domain-Services
         include_management_tools=yes
         include_sub_features=yes
         state=present
    register: result
    delegate_to: '{{ dc_address }}'

  - name: Criando Dominio
    win_domain: >
       dns_domain_name='{{ domain_name }}'
       safe_mode_password='{{ recovery_password }}'
    register: ad
    delegate_to: "{{ dc_address }}"

  - name: Reiniciando Instancia
    win_reboot:
     msg: "Installing AD. Rebooting..."
     pre_reboot_delay: 100
    when: ad.changed
    delegate_to: "{{ dc_address }}"

  - name: Config DNS interno
    win_dns_client:
      adapter_names: '*'
      ipv4_addresses:
      - '127.0.0.1'
    delegate_to: '{{ dc_address }}'

  - name: Criando Zona de DNS Reversa
    win_shell: "Add-DnsServerPrimaryZone -NetworkID {{reverse_dns_zone}} -ReplicationScope Forest"
    delegate_to: "{{ dc_address }}"    
    retries: 30
    delay: 60
    register: result           
    until: result is succeeded

  - name: Cria User
    win_domain_user:
      name: "{{item.nome}}"
      password: P@ssw0rd
      state: present
      groups:
       - "{{item.grupo}}"
    loop:
    - { nome: 'spirogiro', grupo: 'Domain Admins' }
    - { nome: 'spyrojaira', grupo: 'Domain Admins' }
    - { nome: 'sql.service', grupo: 'Domain Users' }
    - { nome: 'teste2', grupo: 'Domain Users' }