---
- name: Configura Ambiente IIS
  hosts: iis
  tasks:
    - name: "Alterando hostname e reiniciando"
      win_hostname:
        name: bookshelf-iis
      register: iis
    - win_reboot:
      when: iis.reboot_required 

    - name: "Colocando DNS do dominio na instancia"
      ansible.windows.win_dns_client:
        adapter_names: Ethernet
        dns_servers: ${ip_instancia_interno_ad}

    - name: "Adicionando IIS ao dominio"
      win_domain_membership:
        dns_domain_name: example-gcp.local
        domain_admin_user: spirogiro@example-gcp.local
        domain_admin_password: P@ssw0rd
        state: domain
      register: domain_state
    - win_reboot:
        pre_reboot_delay: 100
      when: domain_state.reboot_required
 
 

