---
- name: Configura hostname SQL1
  hosts: sql1
  tasks:
    - name: "Alterando hostname e reiniciando"
      win_hostname:
        name: bookshelf-sql1
      register: iis
    - win_reboot:
      when: iis.reboot_required 

- name: Configura hostname SQL2
  hosts: sql2
  tasks:
    - name: "Alterando hostname e reiniciando"
      win_hostname:
        name: bookshelf-sql2
      register: iis
    - win_reboot:
      when: iis.reboot_required 

- name: Configura ambiente SQL
  hosts: sql1:sql2
  tasks:
    - name: "Colocando DNS do dominio na instancia"
      ansible.windows.win_dns_client:
        adapter_names: Ethernet
        dns_servers: ${ip_instancia_interno_ad}
        
    - name: "Adicionando SQL ao dominio"
      win_domain_membership:
        dns_domain_name: example-gcp.local
        domain_admin_user: spirogiro@example-gcp.local
        domain_admin_password: P@ssw0rd
        state: domain
      register: domain_state
    - win_reboot:
        pre_reboot_delay: 100
      when: domain_state.reboot_required

    - name: Adiciona regras de firewall do Windows
      ansible.windows.win_powershell:
        script: |
          netsh advfirewall firewall add rule name="5022 for Avail Groups" dir=in action=allow protocol=TCP localport=5022
          netsh advfirewall firewall add rule name="1433 for SQL Server" dir=in action=allow protocol=TCP localport=1433

    - name: Instala o recurso de cluster de failover
      ansible.windows.win_powershell:
        script: |
          Install-WindowsFeature Failover-Clustering -IncludeManagementTools
    
    - name: Reinicia Instancias
      ansible.windows.win_reboot:
        pre_reboot_delay: 100
 