---
- name: Configura hostname SQL1
  hosts: sql1
  tasks:
    - name: "Alterando hostname e reiniciando"
      win_hostname:
        name: bookshelf-sql1
      register: iis
    - win_reboot:
      when: iis.reboot_required 

- name: Configura hostname SQL2
  hosts: sql2
  tasks:
    - name: "Alterando hostname e reiniciando"
      win_hostname:
        name: bookshelf-sql2
      register: iis
    - win_reboot:
      when: iis.reboot_required
    
    - name: Cria pasta para backups de banco de dados e compartilha
      ansible.windows.win_powershell:
        script: |
          New-Item -ItemType directory -Path C:\SQLBackup
          New-SMBShare -Name SQLBackup -Path C:\SQLBackup -FullAccess "Authenticated Users"

#    - name: Reinicia SQL2 para concluir instalações
#      ansible.windows.win_reboot:
#        pre_reboot_delay: 100

- name: Configura ambiente SQL
  hosts: sql1:sql2
  tasks:
    - name: "Colocando DNS do dominio na instancia"
      ansible.windows.win_dns_client:
        adapter_names: Ethernet
        dns_servers: ${ip_instancia_interno_ad}

    - name: Adiciona regras de firewall do Windows
      ansible.windows.win_powershell:
        script: |
          netsh advfirewall firewall add rule name="5022 for Avail Groups" dir=in action=allow protocol=TCP localport=5022
          netsh advfirewall firewall add rule name="1433 for SQL Server" dir=in action=allow protocol=TCP localport=1433

    - name: Instala o recurso de cluster de failover
      ansible.windows.win_powershell:
        script: |
          Install-WindowsFeature Failover-Clustering -IncludeManagementTools

    - name: Cria as pastas para os dados e arquivos de registro do SQL Server
      ansible.windows.win_powershell:
        script: |
          New-Item -ItemType directory -Path C:\SQLData
          New-Item -ItemType directory -Path C:\SQLLog    

    - name: "Adicionando SQL ao dominio"
      win_domain_membership:
        dns_domain_name: example-gcp.local
        domain_admin_user: spirogiro@example-gcp.local
        domain_admin_password: P@ssw0rd
        state: domain
      register: domain_state
    - win_reboot:
        pre_reboot_delay: 100
      when: domain_state.reboot_required


- name: Configura Cluster SQL1
  hosts: sql1
  tasks:
    - name: Ingressando SQL1 ao Cluster
      ansible.windows.win_powershell:
        script: |
          $node1 = "bookshelf-sql1"
          $node2 = "bookshelf-sql2"

          $nameWSFC = "bookshelf-dbclus"

          $ipWSFC1 = "10.3.0.4"
          $ipWSFC2 = "10.4.0.4"
          $ipWSListener1 = "10.3.0.5"
          $ipWSListener2 = "10.4.0.5"

          $SQLServer1IsReady=$False
          For ($i=0; $i -le 30; $i++) {
              $SqlCatalog = "master"
              $SqlConnection = New-Object System.Data.SqlClient.SqlConnection
              $SqlConnection.ConnectionString = "Server = $node1;" + `
                   "Database = $SqlCatalog; Integrated Security = True"
              try {
                  $SqlConnection.Open()
                  Write-Host "Connection to the server $node1 was successful"
                  $SQLServer1IsReady=$True
                  $SqlConnection.Close()
                  break
              }
              catch {
                  Write-Host "SQL server $node1 is not ready, waiting for 60s"
                  Start-Sleep -s 60 #Wait for 60 seconds
              }
          }
          if($SQLServer1IsReady -eq $False) {
              Write-Error "$node1 is not responding. Was it deployed correctly?"
          }
    

    

 