name: 'Teste'

on:
  push:
    branches:
      - "dev"

jobs:
  golang:
    name: 'Teste'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.16.1'
    - run: go run monitora.go