name: 'Terraform Apply - Desevolvimento'

on:
  push:
    branches:
    - dev


jobs:
  packer-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checa codigo fonte
        uses: "actions/checkout@v3"

      - name: Configura autenticação no GCP
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_DEV }}

      - name: Montando imagem
        uses: "rastogiji/gcp-packer-github-actions@v1.0.1"
        with:
          main_file: ./packer/pkr-ad-imagem.json
          variable_file: ./ambientes/dev/vars-dev.json
          working_directory: .
  
  terraform:
    name: 'Terraform - Desevolvimento'
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: GoLang
      uses: actions/setup-go@v3
      with:
        go-version: '1.16.1'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      env:
        terraform_version: 0.15.5 

 #   - name: Setup Google Cloud
 #     uses: actions-hub/gcloud@master
  #    env:
  #      PROJECT_ID: "develop-348618"
  #      APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_DEV }}
      
    - name: Terraform Init
      run: terraform init -backend=true -backend-config="ambientes/dev/backend.tf"
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_DEV }}
    
    - name: Terraform Format
      run: terraform fmt

    - name: Terraform Plan
      run: terraform plan -var-file=ambientes/dev/vars-dev.tfvars -out "iis-lb.txt"
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_DEV }}

    - name: Terraform Apply
      run: terraform apply "iis-lb.txt"
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_DEV }}
    
   # - name: 'Teste'
     # run: go run monitora.go
     
    - name: Terraform Destroy
      run: terraform destroy -var-file=ambientes/dev/vars-dev.tfvars -auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_DEV }}